task: classification # classification/survival
task_settings:
  outcomes: ["os_months_24"]
  # events: DEATH_EVENT_OC # survival only variable
  loss: mm_loss # mm_survival_loss  mm_loss
  # save_monitor: c_index  # survival only variable

training_type: standard # hyperparameter_tuning  # cross_validation_stratified
data-type: hypothesis_driven  # hypothesis_driven/data_driven
source: pyrad  # pyrad/foundation
imp: noimp  # noimp/imp
seed: [0]

use_early_stopping: true
prepare_dataset: true

train_df: [ "../data/features_dataset_radpy_fixed.parquet", "../data/features_dataset_fmrad.parquet" ]
annotation_file: ../data/annotations.csv

mods:
    # RWD
  - rwd: true
    radpy: false
    dp: false
    genomics: false
    # RWD_DP
  - rwd: true
    radpy: false
    dp: true
    genomics: false
    # RWD_FMRAD
  - rwd: true
    radfm: true
    dp: false
    genomics: false
    # RWD_PYRAD
  - rwd: true
    radpy: true
    dp: false
    genomics: false
    # RWD_DP_FMRAD
  - rwd: true
    radfm: true
    dp: true
    genomics: false
    # RWD_DP_PYRAD
  - rwd: true
    radpy: true
    dp: true
    genomics: false
    # RWD_RADFM_DP_GENOMICS
  - rwd: true
    radfm: true
    dp: true
    genomics: true
    # RWD_RADPY_DP_GENOMICS
  - rwd: true
    radpy: true
    dp: true
    genomics: true
    # RWD_RADFM_DP_GENOMICS
  - rwd: true
    radfm: true
    dp: true
    genomics: true
    # RWD_RADPY_DP_GENOMICS
  - rwd: true
    radpy: true
    dp: true
    genomics: true

  
folds:
  cross_validation:
    - GHD
    - INT
    - MH
    - SZMC
    - VHIO
  standard:
    - ALL

# default hyperparameters
hyperparameters_default:
  batch_size: 16
  reconstruction_weight: 0.1
  n_layers: 2

