task: classification # classification/survival
task_settings:
  outcomes: [ "os_months_6", "os_months_24", "DCR", "ORR" ]
  loss: mm_loss # mm_survival_loss  mm_loss

training_type: cross_validation # hyperparameter_tuning  # cross_validation_stratified
data-type: hypothesis_driven  # hypothesis_driven/data_driven
source: pyrad  # pyrad/foundation
imp: noimp  # noimp/imp
seed: [0]

use_early_stopping: true
prepare_dataset: true

train_df: [ "../data/features_dataset_radpy_fixed.parquet", "../data/features_dataset_fmrad.parquet" ]
annotation_file: ../data/annotations.csv

mods:
  - cb: true # cb: true
    radpy: false
    dp: false
    genomics: false
  - cb: true # cb: true
    radpy: false
    dp: true
    genomics: false
  - cb: true # cb: true
    radpy: true
    dp: false
    genomics: false
  - cb: true # cb: true
    radpy: true
    dp: true
    genomics: false
  - cb: true # cb: true
    radpy: true
    dp: true
    genomics: true
  - cb: true # cb: true
    radfm: true
    dp: false
    genomics: false
  - cb: true # cb: true
    radfm: true
    dp: true
    genomics: false
  - cb: true # cb: true
    radfm: true
    dp: true
    genomics: true

  
folds:
  cross_validation:
    - INT_sub1
    - INT_sub2
    - INT_sub3
    - INT_sub4
    - INT_sub5
  standard:
    - ALL

# default hyperparameters
hyperparameters_default:
  batch_size: 16
  reconstruction_weight: 0.1
  n_layers: 2

